Global:
  use_gpu: True
  epoch_num: 100
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /content/gdrive/MyDrive/VietnamesePaddleOCR/output/ABINet
  save_epoch_step: 20
  # evaluation is run every 2000 iterations
  eval_batch_step: [800, 400]
  cal_metric_during_train: True
  pretrained_model: /content/gdrive/MyDrive/VietnamesePaddleOCR/pretrained_models/rec_r45_abinet_train/best_accuracy
  checkpoints:
  save_inference_dir: /content/gdrive/MyDrive/VietnamesePaddleOCR/inference/ABINet/
  use_visualdl: False
  infer_img: doc/imgs_words_en/word_10.png
  # for data or label process
  character_dict_path: /content/gdrive/MyDrive/VietnamesePaddleOCR/ppocr/utils/dict/vn_dictionary.txt
  character_type: vi
  max_text_length: &max_text_length 25
  infer_mode: False
  use_space_char: True
  save_res_path: /content/gdrive/MyDrive/VietnamesePaddleOCR/output/rec/predicts_abinet.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.99
  clip_norm: 20.0
  lr:
    name: Piecewise
    decay_epochs: [6]
    values: [0.0001, 0.00001]
  regularizer:
    name: 'L2'
    factor: 0.

Architecture:
  model_type: rec
  algorithm: ABINet
  in_channels: 3
  Transform:
  Backbone:
    name: ResNet45
  Head:
    name: ABINetHead
    use_lang: True
    iter_size: 3
    max_length: *max_text_length
    image_size: [ &h 32, &w 128 ]  # [ h, w ]


Loss:
  name: CELoss
  ignore_index: &ignore_index 100 # Must be greater than the number of character classes

PostProcess:
  name: ABINetLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /content/gdrive/MyDrive/VietnamesePaddleOCR/train/img_crop
    label_file_list: /content/gdrive/MyDrive/VietnamesePaddleOCR/train/crop_label.txt
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - ABINetRecAug:
      - ABINetLabelEncode: # Class handling label
          ignore_index: 100
      - ABINetRecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /content/gdrive/MyDrive/VietnamesePaddleOCR/train/img_crop_test
    label_file_list: /content/gdrive/MyDrive/VietnamesePaddleOCR/train/crop_label_test.txt 
    transforms:
      - DecodeImage: # load image
          img_mode: RGB
          channel_first: False
      - ABINetLabelEncode: # Class handling label
          ignore_index: 100
      - ABINetRecResizeImg:
          image_shape: [3, 32, 128]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 4
    use_shared_memory: False
