Architecture:
  Backbone:
    layers: 50
    name: ResNet_SAST
  Head:
    name: SASTHead
  Neck:
    name: SASTFPN
    with_cab: true
  Transform: null
  algorithm: SAST
  model_type: det
Eval:
  dataset:
    data_dir: ../../train/vietnamese/test_image
    label_file_list:
    - ../../train/vietnamese/test_label.txt
    name: SimpleDataSet
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - DetLabelEncode: null
    - DetResizeForTest:
        resize_long: 1536
    - NormalizeImage:
        mean:
        - 0.485
        - 0.456
        - 0.406
        order: hwc
        scale: 1./255.
        std:
        - 0.229
        - 0.224
        - 0.225
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    batch_size_per_card: 1
    drop_last: false
    num_workers: 1
    shuffle: false
Global:
  cal_metric_during_train: false
  checkpoints: ../../output/SAST/latest
  epoch_num: 100
  eval_batch_step:
  - 4000
  - 5000
  infer_img: null
  log_smooth_window: 20
  pretrained_model: ../../pretrained_models/det_r50_vd_sast_icdar15_v2.0_train/best_accuracy
  print_batch_step: 2
  save_epoch_step: 10
  save_inference_dir: ../../inference/SAST/
  save_model_dir: ../../output/SAST/
  save_res_path: ../../output/predictions/det_rec_results/SAST.txt
  use_gpu: true
  use_visualdl: false
Loss:
  name: SASTLoss
Metric:
  main_indicator: hmean
  name: DetMetric
Optimizer:
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0001
  name: Adam
  regularizer:
    factor: 0
    name: L2
PostProcess:
  expand_scale: 0.2
  name: SASTPostProcess
  nms_thresh: 0.5
  sample_pts_num: 2
  score_thresh: 0.5
  shrink_ratio_of_width: 0.15
Train:
  dataset:
    data_dir: ../../train/vietnamese/train_images
    label_file_list:
    - ../../train/vietnamese/train_label.txt
    name: SimpleDataSet
    ratio_list:
    - 1
    transforms:
    - DecodeImage:
        channel_first: false
        img_mode: BGR
    - DetLabelEncode: null
    - SASTProcessTrain:
        image_shape:
        - 512
        - 512
        max_text_size: 512
        min_crop_side_ratio: 0.3
        min_crop_size: 24
        min_text_size: 4
    - KeepKeys:
        keep_keys:
        - image
        - score_map
        - border_map
        - training_mask
        - tvo_map
        - tco_map
  loader:
    batch_size_per_card: 8
    drop_last: false
    num_workers: 1
    shuffle: false
